services:
  - type: web
    name: tcc-apresentacao
    env: node
    plan: free
    buildCommand: npm run build
    startCommand: npm run preview
    root: ia-na-escola---apresentação (2)
    publish: ia-na-escola---apresentação (2)/dist
